sudo: required
language:
- java
- node_js
node_js:
- '4.5'
services:
- docker
script:
- bash ./build.sh
- bash ./docker_build.sh
env:
  global:
  - secure: KubLpnyBXtMUSGhfw7KmfEkxDKJjkEFvGO2QqCnYgNlhB1wliV33z2ELi4sxUyGSjTX+8RnJ/KBB5Gku8RCPHMwXMazop9ijSPimqTbxgXdWI4yFXuBAMZs07dh5GRkjsw8qz8BaphvMUsDFYjrdJSuoTzC7fv8mtkYW+ZChkd4sOB+DB5fgAZe8hJbDn9M9zsKWei4OeI32TfXrEf2Ze53FSSkM+HCk3ndFy+zidBUqPtTV6/6TVffotSw70sdaIj9gkUbUNrT3+bbERs0RHIYq7BdDMekccbLa2UsWq1cQPBXrU8iMrOX33ChI3f/iR1nPOGFSeX1wPgZ+BFwKhjSXidaNCe1/ZvbhPkvU9+uXwgru4vc2NE5YNGQwMWYVihIjMUSQ4fdIGmDt49pp3TiHQy7LDoI5iHwBUKXyVbxKLUSTXKFlmDP1p49mi4T9F492dS3vrO44rgAFL9vKpinjJan24xRL8UC8HbSUo4JrQY2T9ndtbvu5wzi8XSVpv4nfj3yZo0quDdrZx4K1AYlf8aL/J3bqdDygJvlvyEZkBKn87S7tFd/SwiT/BR6jarTxvUlN4XkHVl97BYkrEWKE2mfxvyX0W5gZKeu6eamCaTGQic1Kz7Eg5iz1tlkfPkzK9gGw25Cu8tMcszS1recfBzJnt6Itj+wtvUZ99Cw=
  - secure: PvWxl24YKd7vxQuOSLSgc2kTEgjjOuwOB05W+irXAnV6MHYTYPWHH6BEac+nwci4ratb8b77WBwSGcrRFXAr+Z8tejTOwMbZ6WtAbJ6ziiTDaLVRUgH0aMroZVKTWQD/4+nfOj297eBHO8+o4ENAVTtfjfEz7oM8CXZJzHwLIrBRmed8B6YhH8QtCCITod4i4gooQzfeLN1QwHDzdAxJhqnSDeL6pZiKqxQ9ziLUeZUWgorl0W2Xq+d9vjPt7iyuGX7fu58rTEHo41xYLXhhdHoAfANIufOXBH2AshPlqAa07FbpZcS4Vo0w0YY+t1UfswlFTvZcDnDs4mmHBCkxJeXRsOL1Lz0mV3dg9nHcOUq7sqW/vaeLVqpfLNDVRbaXBnKgVx+rIjVDEEg74FcCi+BVIeTzmzA9u/fty2h/P6CKYSjkBtwlSy1zhftwvBHrRPQQQj830eYpulk7LdYn/MFUrpJyx9lS8uYQKxMgwR80/6LSBJgy53YhTLaxVdGPRzV5jIpG01c6StyQXfjR49UErrpAdnZuybmxd4MV4kgV2Ad6Uhe2+ta69R1EVRRAItqQ1oxdKBFlcgNEyud2DIPiNfkvon4XeZQmM0cbbtTxhf8sELF1z0oNtvcJaGBHuqWyYAlBAuWyufEXaIaFGUF4hheXdwmKtU922O0TZI4=
